#KNOCKBACK CONFIGURATION
knockbackHorizontal: 0.66
knockbackVertical: 1
knockbackVerticalLimit: 0.355
knockbackExtraHorizontal: 0.0
knockbackExtraVertical: 0.0

#Horizontal Knockback Multipliers Only
#Dont ask for vertical ones or ur retarded
knockbackSpeedMultiplier: 1.83
kbspeedsprintmultiplier: 1.0


#1.16+ option idk who uses this
enable-knockback-resistance: false


#Damage Delay In Ticks
#Disable this if you have other plugins Managing this.
enable-damage-ticks: true
max_no_damage_ticks: 20.5

#Bow Boosting fix
#requires restart or PLUGMAN RELOAD
bow-boosting-fix: true
#this can be reloaded this /pvpenhanced reload
#sometimes might break while reloading so dont reload the plugin IG restart the server
bowboost-horizontal: 1.75
bowboost-vertical: 1.25

#Potion Throw optimiser
#currently doesnt work
optimize-pot-throw: true